export const types = {
  ADD_USER: "ADD_USER",
  ADD_USER_TO_LIST: "ADD_USER_TO_LIST",
  ENTER_ROOM: "ENTER_ROOM",
  UPDATE_USER_VOTES: "UPDATE_USER_VOTES",
  UPDATE_ALL_VOTES: "UPDATE_ALL_VOTES",
  RESET_VOTES: "RESET_VOTES",
  RESET_USER_VOTES: "RESET_USER_VOTES",
  GET_ALL_USERS: "GET_ALL_USERS",
};
