name: Automated Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          ref: main

      - name: Update Version
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.PAT }}
          git-message: 'chore(release): {version}'
          git-user-name: ${{ secrets.GH_USERNAME }}
          git-user-email: ${{ secrets.GH_EMAIL }}
          preset: 'angular'
          tag-prefix: 'v'
          release-count: '10'
          version-file: './versions.json'
          skip-on-empty: 'false'
          skip-version-file: 'false'
          skip-commit: 'false'
